CREATE TABLE [dbo].[Counts] (
    [CountsID]   INT NOT NULL,
    [one]        INT NOT NULL,
    [two]        INT NOT NULL,
    [three]      INT NOT NULL,
    [four]       INT NOT NULL,
    [five]       INT NOT NULL,
    [six]        INT NOT NULL,
    [seven]      INT NOT NULL,
    [eight]      INT NOT NULL,
    [nine]       INT NOT NULL,
    [ten]        INT NOT NULL,
    [eleven]     INT NOT NULL,
    [twelve]     INT NOT NULL,
    [thirteen]   INT NOT NULL,
    [fourteen]   INT NOT NULL,
    [fifteen]    INT NOT NULL,
    [sixteen]    INT NOT NULL,
    [seventeen]  INT NOT NULL,
    [eighteen]   INT NOT NULL,
    [nineteen]   INT NOT NULL,
    [twentyPlus] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([CountsID] ASC)
);

