//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FingerprintLite13Entities : DbContext
    {
        public FingerprintLite13Entities()
            : base("name=FingerprintLite13Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grouping> Groupings { get; set; }
        public virtual DbSet<Grouping_Grouping> Grouping_Grouping { get; set; }
        public virtual DbSet<Text> Texts { get; set; }
        public virtual DbSet<Text_Grouping> Text_Grouping { get; set; }
        public virtual DbSet<WordCount> WordCounts { get; set; }
    }
}
