//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FingerprintEntities1 : DbContext
    {
        public FingerprintEntities1()
            : base("name=FingerprintEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<File_Group> File_Group { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Group_Group> Group_Group { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<NumbersWithoutQuote> NumbersWithoutQuotes { get; set; }
        public virtual DbSet<NumbersWithQuote> NumbersWithQuotes { get; set; }
    }
}
