//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FingerprintV8Entities : DbContext
    {
        public FingerprintV8Entities()
            : base("name=FingerprintV8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Count> Counts { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Group_Group> Group_Group { get; set; }
        public virtual DbSet<Text> Texts { get; set; }
    }
}
