//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Group
    {
        public int GG_ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> ChildID { get; set; }
        public int GroupGroupID { get; set; }
        public int GroupGroupID1 { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Group Group1 { get; set; }
    }
}
