//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grouping_Grouping
    {
        public long Id { get; set; }
        public long ParentId { get; set; }
        public long ChildId { get; set; }
    
        public virtual Grouping Grouping { get; set; }
        public virtual Grouping Grouping1 { get; set; }
    }
}
