//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumbersWithoutQuote
    {
        public int FileID { get; set; }
        public Nullable<int> one { get; set; }
        public Nullable<int> two { get; set; }
        public Nullable<int> three { get; set; }
        public Nullable<int> four { get; set; }
        public Nullable<int> five { get; set; }
        public Nullable<int> six { get; set; }
        public Nullable<int> seven { get; set; }
        public Nullable<int> eight { get; set; }
        public Nullable<int> nine { get; set; }
        public Nullable<int> ten { get; set; }
        public Nullable<int> eleven { get; set; }
        public Nullable<int> twelve { get; set; }
        public Nullable<int> thirteen { get; set; }
        public Nullable<int> fourteen { get; set; }
        public Nullable<int> fifteen { get; set; }
        public Nullable<int> sixteen { get; set; }
        public Nullable<int> seventeen { get; set; }
        public Nullable<int> eighteen { get; set; }
        public Nullable<int> nineteen { get; set; }
        public Nullable<int> twentyPlus { get; set; }
    
        public virtual File File { get; set; }
    }
}
