//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerPrint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Text()
        {
            this.Text_Group = new HashSet<Text_Group>();
        }
    
        public int TextID { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public bool QuoteInd { get; set; }
        public int CountsWithQuotesID { get; set; }
        public int CountsWithoutQuotesID { get; set; }
    
        public virtual Count Count { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Text_Group> Text_Group { get; set; }
        public virtual Count Count1 { get; set; }
    }
}
